bin.js, lib/format.js, lib/listChangedFiles.js
Add `--license` option to `ace format`
- accepts license file path as an argument
=> Add `--license` option to `ace format`

lib/webpack.config.js
Projects that have dependencies on upstream modules (where the code lives in node_modules) do not refresh the dev server when the upstream module gets updated.
In a project that uses `ace`, edit a file in `node_modules` and watch the dev server update.
To test a PR of ace, update the dependency location in your `package.json` like so: 
```json
"@connexta/ace": "Bdthomson/ace#dev-server-ignored",
```
=> Remove node_modules from dev server ignored files

lib/webpack.config.js
- Maintains `catalog-ui-search` as part of the whitelist
- Adds `imperio` to the whitelist for temporary use, should be migrated
to `@connexta/imperio`.
- Adds a general rule to include `@connexta` packages
=> Generalize webpack build exclusions into a whitelist

lib/package-utils.js
See https://yarnpkg.com/blog/2018/02/15/nohoist/
Example
```
"workspaces": {
"packages": ["packages/*"],
"nohoist": ["**/react-native", "**/react-native/**"]
}
```
=> Adds support for workspaces with hoisting

lib/bundle.js, lib/package-utils.js, lib/start.js, lib/webpack.config.js
Keep these commits separate.
First adds extensions to the whitelist using package json.
Second adds a quick fix (better fix to come) for yarn linking packages.
=> Whitelisting and alias

lib/storybook/index.js
Dev servers default to 8080, storybook should not also be on 8080.
=> Change default port of storybook from 8080 to 8081

lib/disable-idp.js
Without this, running dev servers in other web context policies like `/admin` were still being blocked.
=> Set all authentication types to BASIC

lib/gen-feature.js, test/ace.spec.js
gen-feature will now exclude the root module if is not a bundle.
=> Improve gen-feature to support non-root bundle

lib/storybook/webpack.config.js
Fixes incorrect reference to wrong webpack config for storybook. Changes to Ace updated the references to get client/server webpack configs, and the relative path was incorrect, causing a failure when booting storybook.
=> Updating storybook with correct webpack config

package.json
This effectively resolves the downstream conflicts in typescript applications and even produces a smaller webpack package as demonstrated in testing.
This resolves issue: https://github.com/connexta/ace/issues/57
=> Moved storybook type packages to devDependencies

lib/webpack.config.js
- This is useful for applications relying on ace, and exposes possibilities like knowing the context-path.  If you know the context-path, you can account for reverse proxy usage.
=> Add package details as variable __package__

lib/webpack.config.js
There are downstream consumers that do not have a context path
=> Fixed issues with context path being required

bin.js, lib/gen-feature.js
Slight updates to gen-feature to allow passing in multiple files to extend from, and to make it so we don't have to name bundles that are being replaced by local bundles differently (by making the filtering of exclusions only happen on the pass in files).
=> Updates gen-feature to allow an array of files to extend from, and to only filter exclusions from those files 

@storybook/react.tsx, package.json, yarn.lock
to allow for `allowJs` and `delcaration` options at the same time
=> Bump typescript version

lib/package.js
=> ACE-79 Loosens version range restriction for org.eclipse.jetty.servlet package

bin.js
We switched some of our repos to use  revision plugin for releases see https://maven.apache.org/maven-ci-friendly.html the drawback is that the pom.xml doesn't have the version you have to grab the version from .flattend-pom.xml generated by this plugin https://www.mojohaus.org/flatten-maven-plugin/. This change just adds support for reading the .flattend-pom.xml
=> Support using flattened pom for repo's using revisions plugin.

lib/webpack.config.js
- The css / less rule isn't correctly merged, so instead this will ensure it doesn't conflict and we accidentally use the style loader in production.
=> Update base to only include css less rule when not production

lib/bundle.js
- Webpack does not set this, but the processes it calls (like tailwind) need it to be set.
- See https://github.com/webpack/webpack/issues/7074 for a long thread on this
=> Explicitly set the node environment variable

prettierrc.js
NOTE: I suspect the issue here is that we have mixed line endings downstream. We may want to investigate making them all conform to LF. For now, this should resolve the issue.
1. Downstream, pull master and point ace at this commit (Note: it is important that you do not format)
1. In the inner ui repo, `yarn install --force`
1. Then ` yarn format -w`. You should not see any diffs.
=> Reverts prettier endOfLine to previous default (pre version 2.0.0)

lib/spec-loader.js, package.json, yarn.lock
- Otherwise the tests will crash.  Mostly useful for tests compiled from typescript.
=> Update spec loader to remove source map comments

lib/webpack.config.js
In some environments, the output from this command is "%cI" instead of the properly formatted date.  This is believed to be due to the % character not being escaped.
=> Escapes % in release date command
